/*
Copyright 2015 Samitha W. Ekanayake

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 */

package com.spiyki.researchnote.gui;

import com.spiyki.researchnote.utils.*;
import com.spiyki.researchnote.data.*;
import javax.swing.table.TableColumn;
import javax.swing.JFileChooser;
import java.io.*;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author  samitha_2
 */
public class AddEditArticle extends javax.swing.JInternalFrame {
    Boolean bEditMode=false;
    Boolean bInitOK=false;
    int CurrentAID=0;
    MainFunctions thisFunctions;
    ViewArticleForm thisArticleViewer;
    String[] strArticleTypes={ "Journal Article", "Book", "Book Chapter", "Conference", "Technical Report", "Thesis" };
    /** Creates new form AddEditArticle */
    public AddEditArticle(MainFunctions envMainFunctions, ViewArticleForm ArticleViewer) {
        initComponents();
        thisFunctions=envMainFunctions;        
        thisArticleViewer=ArticleViewer;
        cmdHelp.setVisible(false);
        this.setLocation(160, 0);        
        cmbArticleType.setModel(new javax.swing.DefaultComboBoxModel(strArticleTypes));
        InitArticleTable();
    }

    private void InitArticleTable(){
        Object[][] data=new Object[15][2];
        data[1][0] = "Author(s)";
        data[0][0] = "Title";
        data[2][0] = "Journal";
        data[3][0] = "Year";
        data[4][0] = "Month";
        data[5][0] = "Pages";
        data[6][0] = "Volume";
        data[7][0] = "Number/Issue";
        data[8][0] = "Series Title";
        data[9][0] = "Publisher";
        data[10][0] = "Publisher Address";
        data[11][0] = "Editors";
        data[12][0] = "DOI";
        data[13][0] = "Keywords";
        data[14][0] = "Abstract";
        if(!bInitOK){
            for(int i=0;i<15;i++){
                    data[i][1]="";
            }
            bInitOK=true;
        }else{
            for(int i=0;i<15;i++){
                data[i][1]=(String)tblArticleDetails.getValueAt(i, 1);
            }
        }
        switch(cmbArticleType.getSelectedIndex()){         
            case 0:

                break;
            case 1:
                data[0][0] = "Not Applicable";
                data[2][0] = "Book Title";
                data[7][0] = "Edition";
                break;
            case 2:
                data[2][0] = "Book Title";
                data[7][0] = "Edition";                
                break;
            case 3:
                data[2][0] = "Conference";
                break;
            case 4:
                
                break;
            case 5:
                
                break;
            case 6:
                
                break;
            case 7:
                
                break;                
        }

        tblArticleDetails.setModel(new javax.swing.table.DefaultTableModel(
            data,
            new String [] {
                "Item", "Value"
            }
        ));        
        TableColumn column = null;
        column = tblArticleDetails.getColumnModel().getColumn(0);
        column.setPreferredWidth(200); //third column is bigger
        column = tblArticleDetails.getColumnModel().getColumn(1);
        column.setPreferredWidth(530); //third column is bigger
        tblArticleDetails.setRowHeight(14, 200);  
    }
    
public void PopulateArticleDetails(int AID, String[] strArticleInfo, Boolean isInCurrentProject){
    CurrentAID=AID;
    cmbArticleType.setSelectedItem((String)strArticleInfo[0]);
    for(int i=0;i<15;i++){
        tblArticleDetails.setValueAt(strArticleInfo[i+1],i, 1);
    }
    chkAddToCurrentProject.setSelected(isInCurrentProject);
    bEditMode=true;
//    cmdAdd.setText("Save");
}    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblArticleDetails = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cmbArticleType = new javax.swing.JComboBox();
        cmdClose = new javax.swing.JButton();
        chkAddToCurrentProject = new javax.swing.JCheckBox();
        cmdAdd = new javax.swing.JButton();
        cmdBrowse = new javax.swing.JButton();
        cmdHelp = new javax.swing.JButton();
        txtPDFLocation = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setPreferredSize(new java.awt.Dimension(760, 605));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(null);
        jScrollPane1.setOpaque(false);

        tblArticleDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblArticleDetails.setOpaque(false);
        jScrollPane1.setViewportView(tblArticleDetails);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 740, 460));

        jLabel1.setText("Article Type");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        cmbArticleType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbArticleType.setBorder(null);
        cmbArticleType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbArticleTypeActionPerformed(evt);
            }
        });
        cmbArticleType.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbArticleTypePropertyChange(evt);
            }
        });
        getContentPane().add(cmbArticleType, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, 170, 20));

        cmdClose.setIcon(new javax.swing.ImageIcon(getClass().getResource(MainFunctions.IMAGE_PATH + "CloseWindow.jpg"))); // NOI18N
        cmdClose.setToolTipText("Close");
        cmdClose.setBorder(null);
        cmdClose.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource(MainFunctions.IMAGE_PATH + "CloseWindow_R.jpg"))); // NOI18N
        cmdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCloseActionPerformed(evt);
            }
        });
        getContentPane().add(cmdClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, 80, 80));

        chkAddToCurrentProject.setBackground(new java.awt.Color(204, 204, 204));
        chkAddToCurrentProject.setText("Include into the current project");
        chkAddToCurrentProject.setOpaque(false);
        getContentPane().add(chkAddToCurrentProject, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, -1, -1));

        cmdAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource(MainFunctions.IMAGE_PATH + "ArticleAddOKBut_N.jpg"))); // NOI18N
        cmdAdd.setToolTipText("Add/save article");
        cmdAdd.setBorder(null);
        cmdAdd.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource(MainFunctions.IMAGE_PATH + "ArticleAddOKBut_P.jpg"))); // NOI18N
        cmdAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddActionPerformed(evt);
            }
        });
        getContentPane().add(cmdAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 80));

        cmdBrowse.setIcon(new javax.swing.ImageIcon(getClass().getResource(MainFunctions.IMAGE_PATH + "PDFPathBut_N.jpg"))); // NOI18N
        cmdBrowse.setToolTipText("Browse");
        cmdBrowse.setBorder(null);
        cmdBrowse.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource(MainFunctions.IMAGE_PATH + "PDFPathBut_P.jpg"))); // NOI18N
        cmdBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBrowseActionPerformed(evt);
            }
        });
        getContentPane().add(cmdBrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 80, 40));

        cmdHelp.setText("Help");
        cmdHelp.setToolTipText("Help");
        getContentPane().add(cmdHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 80, 80));
        getContentPane().add(txtPDFLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 460, -1));

        jLabel2.setText("PDF File Location");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(MainFunctions.IMAGE_PATH + "ArticleEdit.jpg"))); // NOI18N
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 575));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void cmbArticleTypePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbArticleTypePropertyChange
//    InitArticleTable();
}//GEN-LAST:event_cmbArticleTypePropertyChange

private void cmbArticleTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbArticleTypeActionPerformed
    InitArticleTable();
}//GEN-LAST:event_cmbArticleTypeActionPerformed

private void cmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCloseActionPerformed
    if(thisArticleViewer!=null){
        thisArticleViewer.CloseEditArticleWindow();
    }else{
        try {
            this.setClosed(true);
            this.setVisible(false);
        } catch (java.beans.PropertyVetoException e) {}  
    }
}//GEN-LAST:event_cmdCloseActionPerformed

private void cmdAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddActionPerformed
    String[] ArticleInfo=new String[16];
    tblArticleDetails.setEditingColumn(0);
    ArticleInfo[0]=strArticleTypes[cmbArticleType.getSelectedIndex()];
    for(int i=0;i<15;i++){
        ArticleInfo[i+1]=(String)tblArticleDetails.getValueAt(i, 1);
    }
    
    if(!bEditMode){//If new article
//        thisFunctions.thisUserDatabase.AddArticle(ArticleInfo[0],ArticleInfo[1],ArticleInfo[2],ArticleInfo[3],ArticleInfo[4]
//                                                 ,ArticleInfo[5],ArticleInfo[6],ArticleInfo[7],ArticleInfo[8],ArticleInfo[9]
//                                                 ,ArticleInfo[10],ArticleInfo[11],ArticleInfo[12],ArticleInfo[13],ArticleInfo[14]
//                                                 ,ArticleInfo[15],chkAddToCurrentProject.isSelected());
        
                                                 
    }else{//If editing existing article
//        thisFunctions.thisUserDatabase.UpdateArticleRecord(CurrentAID,ArticleInfo[0],ArticleInfo[1],ArticleInfo[2],ArticleInfo[3],ArticleInfo[4]
//                                                 ,ArticleInfo[5],ArticleInfo[6],ArticleInfo[7],ArticleInfo[8],ArticleInfo[9]
//                                                 ,ArticleInfo[10],ArticleInfo[11],ArticleInfo[12],ArticleInfo[13],ArticleInfo[14]
//                                                 ,ArticleInfo[15],chkAddToCurrentProject.isSelected());
        thisArticleViewer.RefreshProjectList();
    }
    this.setVisible(false);
}//GEN-LAST:event_cmdAddActionPerformed

private void cmdBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBrowseActionPerformed
// TODO add your handling code here:
    JFileChooser thisChooser=new JFileChooser(".");    
    FileFilter filter1 = new ExtensionFileFilter("PDF Files", new String[] { "PDF" });
    thisChooser.setFileFilter(filter1);
    thisChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
    int chooserRes=thisChooser.showOpenDialog(this);
    if(chooserRes==JFileChooser.APPROVE_OPTION){
        File thisFile=thisChooser.getSelectedFile();
        txtPDFLocation.setText(thisFile.getAbsolutePath());
    }
}//GEN-LAST:event_cmdBrowseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkAddToCurrentProject;
    private javax.swing.JComboBox cmbArticleType;
    private javax.swing.JButton cmdAdd;
    private javax.swing.JButton cmdBrowse;
    private javax.swing.JButton cmdClose;
    private javax.swing.JButton cmdHelp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblArticleDetails;
    private javax.swing.JTextField txtPDFLocation;
    // End of variables declaration//GEN-END:variables

}
