/*
Copyright 2015 Samitha W. Ekanayake

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 */

package com.spiyki.researchnote.gui;

import com.spiyki.researchnote.utils.*;
import com.spiyki.researchnote.data.*;
import java.awt.*;
import javax.swing.text.*;
/**
 *
 * @author  samitha_2
 */
public class ViewProjectForm extends javax.swing.JInternalFrame {
    MainFunctions thisFunctions;
    ViewNotesForm thisNoteListWindow=null;
    ExportDataForm thisExportWindow=null;
    int thisPID;
    /** Creates new form ViewProjectForm */
    public ViewProjectForm(MainFunctions envMainFunctions, int iPID) {
        initComponents();
        thisFunctions=envMainFunctions;
        thisPID=iPID;
        this.setLocation(160, 0);
//        cmdEditProject.setVisible(false);
        RefreshProjectDetails();
    }

    private void RefreshProjectDetails(){        
        SimpleAttributeSet italic = new SimpleAttributeSet();
        StyleConstants.setItalic(italic, true);
        StyleConstants.setBold(italic, true);
        String[] thisProjDetails=thisFunctions.thisUserDatabase.GetProjectDescription(thisFunctions.CurrentPID);
        if(thisFunctions.CurrentPID!=0){//A project has been selected          
            this.setTitle(thisProjDetails[0]);
            new DisplayInHTMLformat(thisProjDetails[1], "PDTmp", txtProjectDes);
            append("\n\nDate Created: ",italic);
            append(thisProjDetails[2],italic);
            append("\n\nDate Modified: ",italic);
            append(thisProjDetails[3],italic);
        }else{//No project selected --> show the welcome window (inlcuding help)
            
        }
    }
    
   protected void append(String s, AttributeSet attributes) {
        Document d = txtProjectDes.getDocument();
        try {
          d.insertString(d.getLength(), s, attributes);
          
        } catch (BadLocationException ble) {
        }
  } 
   
   private void OpenNoteListWindow(){
       if(thisNoteListWindow==null){
            thisNoteListWindow=new ViewNotesForm(thisFunctions,thisPID,true);
            thisNoteListWindow.setVisible(true);
            thisFunctions.thisMainWindow.myDeskTop.add(thisNoteListWindow);  
            try {
                thisNoteListWindow.setSelected(true);
            } catch (java.beans.PropertyVetoException e) {}    
       }else{
           if(!thisNoteListWindow.isVisible()){
                thisNoteListWindow=new ViewNotesForm(thisFunctions,thisPID,true);
                thisNoteListWindow.setVisible(true);
                thisFunctions.thisMainWindow.myDeskTop.add(thisNoteListWindow);                
           }
           try {
                thisNoteListWindow.setSelected(true);
           } catch (java.beans.PropertyVetoException e) {}  
       }       
   }    
    
   public void CloseNoteListWindow(){
       if(thisNoteListWindow!=null){           
           try {
            thisNoteListWindow.setClosed(true);
           } catch (java.beans.PropertyVetoException e) {}  
           thisNoteListWindow=null;
       }       
   }   
    
   private void OpenExportWindow(){
       if(thisExportWindow==null){
            thisExportWindow=new ExportDataForm(thisFunctions);
            thisExportWindow.setVisible(true);
            thisFunctions.thisMainWindow.myDeskTop.add(thisExportWindow);  
            try {
                thisExportWindow.setSelected(true);
            } catch (java.beans.PropertyVetoException e) {}    
       }else{
           if(!thisExportWindow.isVisible()){
                thisExportWindow=new ExportDataForm(thisFunctions);
                thisExportWindow.setVisible(true);
                thisFunctions.thisMainWindow.myDeskTop.add(thisExportWindow);                 
           }
           try {
                thisExportWindow.setSelected(true);
           } catch (java.beans.PropertyVetoException e) {}  
       }       
   } 
   
   public void CloseExportWindow(){
       if(thisExportWindow!=null){           
           try {
            thisExportWindow.setClosed(true);
           } catch (java.beans.PropertyVetoException e) {}  
           thisExportWindow=null;
       }       
   }
   
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtProjectDes = new javax.swing.JTextPane();
        cmdExportOptions = new javax.swing.JButton();
        cmdEditProject = new javax.swing.JButton();
        cmdCreateNoteList = new javax.swing.JButton();
        cmdBack = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new Color(255, 255, 255));
        setBorder(null);
        setTitle("Current Project");
        setPreferredSize(new Dimension(600, 500));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setViewportView(txtProjectDes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 580, 360));

        cmdExportOptions.setIcon(new javax.swing.ImageIcon(getClass().getResource(MainFunctions.IMAGE_PATH + "ExportProjectBut_N.jpg"))); // NOI18N
        cmdExportOptions.setToolTipText("Export options");
        cmdExportOptions.setBorder(null);
        cmdExportOptions.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource(MainFunctions.IMAGE_PATH + "ExportProjectBut_P.jpg"))); // NOI18N
        cmdExportOptions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdExportOptionsActionPerformed(evt);
            }
        });
        getContentPane().add(cmdExportOptions, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 80, 80));

        cmdEditProject.setIcon(new javax.swing.ImageIcon(getClass().getResource(MainFunctions.IMAGE_PATH + "EditProjectBut_N.jpg"))); // NOI18N
        cmdEditProject.setToolTipText("Edit project");
        cmdEditProject.setBorder(null);
        cmdEditProject.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource(MainFunctions.IMAGE_PATH + "EditProjectBut_P.jpg"))); // NOI18N
        cmdEditProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEditProjectActionPerformed(evt);
            }
        });
        getContentPane().add(cmdEditProject, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 80, 80));

        cmdCreateNoteList.setIcon(new javax.swing.ImageIcon(getClass().getResource(MainFunctions.IMAGE_PATH + "ProjectNotesBut_N.jpg"))); // NOI18N
        cmdCreateNoteList.setToolTipText("Project notes");
        cmdCreateNoteList.setBorder(null);
        cmdCreateNoteList.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource(MainFunctions.IMAGE_PATH + "ProjectNotesBut_P.jpg"))); // NOI18N
        cmdCreateNoteList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCreateNoteListActionPerformed(evt);
            }
        });
        getContentPane().add(cmdCreateNoteList, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 80));

        cmdBack.setIcon(new javax.swing.ImageIcon(getClass().getResource(MainFunctions.IMAGE_PATH + "CloseWindow.jpg"))); // NOI18N
        cmdBack.setToolTipText("Exit");
        cmdBack.setBorder(null);
        cmdBack.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource(MainFunctions.IMAGE_PATH + "CloseWindow_R.jpg"))); // NOI18N
        cmdBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBackActionPerformed(evt);
            }
        });
        getContentPane().add(cmdBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 80, 80));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(MainFunctions.IMAGE_PATH + "ProjectSelect.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void cmdEditProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEditProjectActionPerformed
// TODO add your handling code here:
    thisFunctions.thisMainWindow.actionEditProjectWindow(thisPID);
}//GEN-LAST:event_cmdEditProjectActionPerformed

private void cmdBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBackActionPerformed
// TODO add your handling code here:
    try {
        this.setClosed(true);
        this.setVisible(false);
    } catch (java.beans.PropertyVetoException e) {}      
}//GEN-LAST:event_cmdBackActionPerformed

private void cmdExportOptionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdExportOptionsActionPerformed
// TODO add your handling code here:
    OpenExportWindow();
}//GEN-LAST:event_cmdExportOptionsActionPerformed

private void cmdCreateNoteListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCreateNoteListActionPerformed
// TODO add your handling code here:
    OpenNoteListWindow();
}//GEN-LAST:event_cmdCreateNoteListActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdBack;
    private javax.swing.JButton cmdCreateNoteList;
    private javax.swing.JButton cmdEditProject;
    private javax.swing.JButton cmdExportOptions;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane txtProjectDes;
    // End of variables declaration//GEN-END:variables

}
