/*
Copyright 2015 Samitha W. Ekanayake

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
 */

package com.spiyki.researchnote.gui;

import com.spiyki.researchnote.utils.*;
import com.spiyki.researchnote.data.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author  samitha_2
 */
public class ViewNotesForm extends javax.swing.JInternalFrame {
    MainFunctions thisFunctions;
    int iItemID;
    Boolean bIsProject;
    ArrayList CurrentNoteList=new ArrayList();
    /** Creates new form ViewNotesForm */
    public ViewNotesForm(MainFunctions envMainFunctions, int ItemID, Boolean bProject) {
        initComponents();
        thisFunctions=envMainFunctions;
        bIsProject=bProject;
        iItemID=ItemID;
        cmdPrintNotes.setVisible(false);
        cmdAddToProject.setVisible(false);
        this.setLocation(160, 0);        
        RefreshNoteList();
    }
    
    public void RefreshNoteList(){
        if(!bIsProject){
            PopulateNotes(thisFunctions.thisUserDatabase.GenerateNoteListForArticles(iItemID,false));
        }else{
            PopulateNotes(thisFunctions.thisUserDatabase.GenerateNoteListForProjects(iItemID));
        }
    }

    private void PopulateNotes(ArrayList NoteList){
        CurrentNoteList=NoteList;
        if(CurrentNoteList.size()!=0){  //Notes available for this article
            int iNotes=CurrentNoteList.size();
            final String[] sNoteTitle=new String[iNotes];
            for(int i=0;i<iNotes;i++){
                sNoteTitle[i]=(String)((ArrayList)CurrentNoteList.get(i)).get(1);
            }
            lstNotes.setModel(new javax.swing.AbstractListModel() {
                String[] strings = sNoteTitle;
                public int getSize() { return strings.length; }
                public Object getElementAt(int i) { return strings[i]; }
            });
            lstNotes.setEnabled(true);
        }else{
            lstNotes.setModel(new javax.swing.AbstractListModel() {
                String[] strings = {"Notes not found."};
                public int getSize() { return strings.length; }
                public Object getElementAt(int i) { return strings[i]; }
            });            
            lstNotes.setEnabled(false);
        }
    }    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        lstNotes = new javax.swing.JList();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNoteDesc = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cmdClose = new javax.swing.JButton();
        cmdAddToProject = new javax.swing.JButton();
        cmdAddNote = new javax.swing.JButton();
        cmdEditNote = new javax.swing.JButton();
        cmdPrintNotes = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBorder(null);
        setTitle("Notes");
        setPreferredSize(new java.awt.Dimension(750, 480));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lstNotes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstNotes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstNotesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lstNotesMouseEntered(evt);
            }
        });
        lstNotes.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstNotesValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstNotes);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 200, 410));

        txtNoteDesc.setEditable(false);
        jScrollPane1.setViewportView(txtNoteDesc);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 430, 410));

        jLabel1.setText("Title");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setText("Note");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        jPanel1.setOpaque(false);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmdClose.setIcon(new javax.swing.ImageIcon(getClass().getResource(MainFunctions.IMAGE_PATH + "CloseWindow.jpg"))); // NOI18N
        cmdClose.setToolTipText("Exit");
        cmdClose.setBorder(null);
        cmdClose.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource(MainFunctions.IMAGE_PATH + "CloseWindow_R.jpg"))); // NOI18N
        cmdClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdCloseActionPerformed(evt);
            }
        });
        jPanel1.add(cmdClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 80, 80));

        cmdAddToProject.setText("N --> P");
        cmdAddToProject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddToProjectActionPerformed(evt);
            }
        });
        jPanel1.add(cmdAddToProject, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 80, 80));

        cmdAddNote.setIcon(new javax.swing.ImageIcon(getClass().getResource(MainFunctions.IMAGE_PATH + "NoteAddBut_N.jpg"))); // NOI18N
        cmdAddNote.setToolTipText("Add new note");
        cmdAddNote.setBorder(null);
        cmdAddNote.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource(MainFunctions.IMAGE_PATH + "NoteAddBut_P.jpg"))); // NOI18N
        cmdAddNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAddNoteActionPerformed(evt);
            }
        });
        jPanel1.add(cmdAddNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 80));

        cmdEditNote.setIcon(new javax.swing.ImageIcon(getClass().getResource(MainFunctions.IMAGE_PATH + "NoteEditBut_N.jpg"))); // NOI18N
        cmdEditNote.setToolTipText("Edit note");
        cmdEditNote.setBorder(null);
        cmdEditNote.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource(MainFunctions.IMAGE_PATH + "NoteEditBut_P.jpg"))); // NOI18N
        cmdEditNote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdEditNoteActionPerformed(evt);
            }
        });
        jPanel1.add(cmdEditNote, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 80, 80));

        cmdPrintNotes.setText("Print");
        cmdPrintNotes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdPrintNotesActionPerformed(evt);
            }
        });
        jPanel1.add(cmdPrintNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 80, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 30, 80, 410));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource(MainFunctions.IMAGE_PATH + "NoteViewForm.jpg"))); // NOI18N
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void cmdAddToProjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddToProjectActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_cmdAddToProjectActionPerformed

private void cmdPrintNotesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdPrintNotesActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_cmdPrintNotesActionPerformed

private void lstNotesValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstNotesValueChanged
// TODO add your handling code here:
    if(!lstNotes.isSelectionEmpty()){
//        int iPID=(Integer)((ArrayList)CurrentNoteList.get(lstNotes.getSelectedIndex())).get(1);
        String sPrjDes=(String)((ArrayList)CurrentNoteList.get(lstNotes.getSelectedIndex())).get(2);
        new DisplayInHTMLformat(sPrjDes, "NLTmp", txtNoteDesc);
    }    
}//GEN-LAST:event_lstNotesValueChanged

private void cmdAddNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAddNoteActionPerformed
// TODO add your handling code here:
    JOptionPane newProjectName=new JOptionPane();
    String strNoteName=newProjectName.showInputDialog(null, "Enter the title of the note", "Title", JOptionPane.DEFAULT_OPTION);
    if(strNoteName!=null){
        if(strNoteName.trim().compareTo("")!=0){
            if(bIsProject){
                LicenceMgmt thisLicTest=new LicenceMgmt();
                if(!thisLicTest.LICENSED){
                    if(thisFunctions.thisUserDatabase.IfProjectNoteCountExeedsNonLicensedLimit(iItemID,thisLicTest)){
                        JOptionPane optionPane = new JOptionPane();
                        optionPane.showMessageDialog(null, "Limit for number of notes reached.\nPlease purchase the full version to remove this limit.", "DEMO version limit", JOptionPane.YES_OPTION);
                    }else{
                        thisFunctions.thisUserDatabase.AddNewNote(strNoteName.trim(), " ", iItemID,true);
                    }
                }else{
                    thisFunctions.thisUserDatabase.AddNewNote(strNoteName.trim(), " ", iItemID,true);
                }                 
//                thisFunctions.thisUserDatabase.AddNewNote(strNoteName.trim(), " ", iItemID,true);
            }else{
                LicenceMgmt thisLicTest=new LicenceMgmt();
                if(!thisLicTest.LICENSED){
                    if(thisFunctions.thisUserDatabase.IfArticleNoteCountExeedsNonLicensedLimit(iItemID,thisLicTest)){
                        JOptionPane optionPane = new JOptionPane();
                        optionPane.showMessageDialog(null, "Limit for number of notes reached.\nPlease purchase the full version to remove this limit.", "DEMO version limit", JOptionPane.YES_OPTION);
                    }else{
                        thisFunctions.thisUserDatabase.AddNewNote(strNoteName.trim(), " ", iItemID,false);
                    }
                }else{
                    thisFunctions.thisUserDatabase.AddNewNote(strNoteName.trim(), " ", iItemID,false);
                }                
//                thisFunctions.thisUserDatabase.AddNewNote(strNoteName.trim(), " ", iItemID,false);
            }
            RefreshNoteList();
        }
    }
}//GEN-LAST:event_cmdAddNoteActionPerformed

private void cmdCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdCloseActionPerformed
// TODO add your handling code here:
    try {
        this.setClosed(true);
        this.setVisible(false);
    } catch (java.beans.PropertyVetoException e) {}  
}//GEN-LAST:event_cmdCloseActionPerformed

private void cmdEditNoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdEditNoteActionPerformed
// TODO add your handling code here:
    ArrayList tmpAdd=new ArrayList();
    tmpAdd.add(this);
    int iNote=(Integer)((ArrayList)CurrentNoteList.get(lstNotes.getSelectedIndex())).get(0);
    tmpAdd.add(txtNoteDesc);
    thisFunctions.thisMainWindow.actionOpenEditorWindow(false, iNote,tmpAdd);    
}//GEN-LAST:event_cmdEditNoteActionPerformed

private void lstNotesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstNotesMouseEntered
// TODO add your handling code here:
}//GEN-LAST:event_lstNotesMouseEntered

private void lstNotesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstNotesMouseClicked
// TODO add your handling code here:
    if(evt.getClickCount()==2){
        int iNote=(Integer)((ArrayList)CurrentNoteList.get(lstNotes.getSelectedIndex())).get(0);
        String strCurrTitle=(String)((ArrayList)thisFunctions.thisUserDatabase.GetNoteDetils(iNote)).get(1);
        JOptionPane optionPane = new JOptionPane();
        String strAns=optionPane.showInputDialog(this, "Enter new title for the note", strCurrTitle);   
        if(strAns!=null){
            thisFunctions.thisUserDatabase.UpdateNote(iNote, strAns, (String)((ArrayList)thisFunctions.thisUserDatabase.GetNoteDetils(iNote)).get(2));
        }
        RefreshNoteList();
    }
    
}//GEN-LAST:event_lstNotesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAddNote;
    private javax.swing.JButton cmdAddToProject;
    private javax.swing.JButton cmdClose;
    private javax.swing.JButton cmdEditNote;
    private javax.swing.JButton cmdPrintNotes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList lstNotes;
    private javax.swing.JTextPane txtNoteDesc;
    // End of variables declaration//GEN-END:variables

}
